# UNIVERSIDAD AUTONOMA DE AGUASCALIENTES
### ING. EN COMPUTACION INTELIGENTE
### CENTRO DE CIENCIAS BASICAS
### APRENDIZAJE INTELIGENTE

Prof. Francisco Javier Luna Rosas

- César Eduardo Elias del Hoyo ID: 262045 
- José Luis Sandoval Pérez ID: 261731 
- Diego Emanuel Saucedo Ortega ID: 261230 
- Carlos Daniel Torres Macias ID: 244543

#### EXAMEN 1ER PARCIAL 
<b>Implementación</b>. Implemente la red neuronal con la 
técnica de propagación hacia atrás (Feed-Forward) 

### Importar librerias

In [1]:
import numpy as np

### Funciones

In [2]:
def f(x):
    """ funcion sigmoide"""
    return 1 / (1 + np.exp(-x))

def f1(x):
    """ derivada de la funcion sigmoide"""
    return f(x) * (1 - f(x))

In [3]:
# variables del programa
N_ENTRADAS = 3
N_OCULTAS = 2
N_SALIDAS = 1
N_CAPAS = 3

TASA_DE_APRENDIZAJE = 0.9


### Declarar los pesos

In [4]:
# inicializar los pesos

# pesos de entrada a capa oculta
W1 = np.array([[0.2,-0.3],
               [0.4,0.1],
               [-0.5,0.2]])

# pesos de capa oculta a la salida
W2 = np.array([-0.3,-0.2])

# declarar bias
B = np.array([-0.4,-0.2,0.1])

# entradas establecidas
X = np.array([1,0,1])

print("Pesos W1:\n",W1)
print("Pesos W2:\n",W2)
print("Bias:\n",B)

Pesos W1:
 [[ 0.2 -0.3]
 [ 0.4  0.1]
 [-0.5  0.2]]
Pesos W2:
 [-0.3 -0.2]
Bias:
 [-0.4 -0.2  0.1]


#### Calcular las salidas

In [5]:
# calculamos la salida de las entradas a las capas ocultas
Z1 = np.dot(X, W1)
# sumamos el bias
Z1[0] += B[0]
Z1[1] += B[1]

# utilizamos la funcion de activacion para obtener la entrada para la capa oculta
A1 = f(Z1)

print("Salida: ",A1)

Salida:  [0.33181223 0.42555748]


In [6]:
# calculamos la salida de la capa oculta a la salida
Z2 = np.dot(A1, W2) + B[2]

# utilizamos la funcion de activacion para obtener la entrada para la salida
A2 = f(Z2)

print("Salida: ",A2)

Salida:  0.47884883888902396


#### Entrenamiento del MLP

In [7]:
# declaramos el valor objetivo
TARGET = 1
EPOCAS = 7000
while A2 != TARGET and EPOCAS>0:
    # propagacion del error
    E6 = TARGET - A2
    E5 = E6 * W2[1] * f1(Z1[1])
    E4 = E6 * W2[0] * f1(Z1[0])
    
    # actualizar pesos y bias
    W1[0,0] = W1[0,0] + TASA_DE_APRENDIZAJE * E4 * X[0]
    W1[0,1] = W1[0,1] + TASA_DE_APRENDIZAJE * E5 * X[0]
    W1[1,0] = W1[1,0] + TASA_DE_APRENDIZAJE * E4 * X[1]
    W1[1,1] = W1[1,1] + TASA_DE_APRENDIZAJE * E5 * X[1]
    W1[2,0] = W1[2,0] + TASA_DE_APRENDIZAJE * E4 * X[2]
    W1[2,1] = W1[2,1] + TASA_DE_APRENDIZAJE * E5 * X[2]
    
    W2[0] = W2[0] + TASA_DE_APRENDIZAJE * E6 * A1[0]
    W2[1] = W2[1] + TASA_DE_APRENDIZAJE * E6 * A1[1]
    
    B[0] = B[0] + TASA_DE_APRENDIZAJE * E4
    B[1] = B[1] + TASA_DE_APRENDIZAJE * E5
    B[2] = B[2] + TASA_DE_APRENDIZAJE * E6
    
    # volvemos a calcular las salidas
    
    # calculamos la salida de las entradas a las capas ocultas
    Z1 = np.dot(X, W1)
    # sumamos el bias
    Z1[0] += B[0]
    Z1[1] += B[1]

    # utilizamos la funcion de activacion para obtener la entrada para la capa oculta
    A1 = f(Z1)
    
    # calculamos la salida de la capa oculta a la salida
    Z2 = np.dot(A1, W2) + B[2]

    # utilizamos la funcion de activacion para obtener la entrada para la salida
    A2 = f(Z2)
    
    EPOCAS -= 1

print(A2)

0.9999441203160521


In [8]:
print("Pesos Entradas:\n",W1,"\n")
print("Pesos Capa Oculta:\n",W2,"\n")
print("Bias:\n",B,"\n")

print("Entradas:",X,"\nSalida:",A2)

Pesos Entradas:
 [[0.92047145 0.61833445]
 [0.4        0.1       ]
 [0.22047145 1.11833445]] 

Pesos Capa Oculta:
 [2.03222604 3.03960186] 

Bias:
 [0.32047145 0.71833445 5.34334643] 

Entradas: [1 0 1] 
Salida: 0.9999441203160521


## Conclusiones

### En este examen utilizamos únicamente la librería numpy, empleamos las funciones sigmoide y declaramos los pesos y los bias que nos permitieron aplicar el algoritmo o modelo de Feed-Forward para el entrenamiento y aprendizaje de la red neuronal para obtener un salida final próxima a 1. Este resultado se obtuvo aplicando el modelo mediante capaz que realizan la transformación de la red de una sola dirección, en este caso hacia adelante y que permitieron llegar a una salida de la red neurona

# Bibliografía

### Coach, I. (15 de Noviembre de 2021). Construcción de una red feedforward en Python. Obtenido de YouTube: https://www.youtube.com/watch?v=U2Cs9kdwmmU